version: '3.7'

services:
  backend:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8050
    volumes:
      - ./src/:/app/
    ports:
      - "8050:8050"
    environment:
      - SUPERADMIN_GH_PAT=${SUPERADMIN_GH_PAT}
      - SUPERADMIN_PWD=superadmin_pwd
      - GH_OAUTH_ID=${GH_OAUTH_ID}
      - GH_OAUTH_SECRET=${GH_OAUTH_SECRET}
      - POSTGRES_URL=postgresql+asyncpg://dummy_login:dummy_pwd@test_db/dummy_db
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DEBUG=true
    depends_on:
      test_db:
        condition: service_healthy

  test_db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=dummy_login
      - POSTGRES_PASSWORD=dummy_pwd
      - POSTGRES_DB=dummy_db
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U dummy_login -d dummy_db'"]
      interval: 10s
      timeout: 3s
      retries: 3
