{
 "title": "Quack API dashboard",
 "description": "API health monitoring dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Overall latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(http_request_duration_highr_seconds_sum{job=\"backend\"}[1h])/rate(http_request_duration_highr_seconds_count{job=\"backend\"}[1h])",
     "legendFormat": "Mean"
    },
    {
     "expr": "histogram_quantile(0.50, rate(http_request_duration_highr_seconds_bucket{job=\"backend\"}[1h]))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.9, rate(http_request_duration_highr_seconds_bucket{job=\"backend\"}[1h]))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95, rate(http_request_duration_highr_seconds_bucket{job=\"backend\"}[1h]))",
     "legendFormat": "p95"
    }
   ]
  },
  {
   "title": "RPM",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(status) (increase(http_requests_total{handler!=\"none\", job=\"backend\"}[1m]))*50/60",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "Route RPM",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 10, "x": 14, "y": 6 },
   "targets": [
    {
     "expr": "increase(http_requests_total{job=\"backend\", handler!=\"none\"}[1m]) * 0.5/0.6",
     "legendFormat": "{{ method }} {{ handler }}"
    }
   ]
  },
  {
   "title": "Route latency",
   "type": "bargauge",
   "gridPos": { "h": 14, "w": 10, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum{job=\"backend\", handler!=\"none\"}[1h]) / rate(http_request_duration_seconds_count{job=\"backend\", handler!=\"none\"}[1h])",
     "legendFormat": "{{ method }} {{ handler }}"
    }
   ]
  },
  {
   "title": "Daily requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_requests_total{handler!=\"none\", job=\"backend\"}[24h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job!=\"prometheus\"}",
     "legendFormat": "mem"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 10, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"backend\"}[30s])",
     "legendFormat": "cpu"
    }
   ]
  },
  {
   "title": "Errors per second",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{status=\"5xx\"}[30s]))",
     "legendFormat": "errors"
    }
   ]
  }
 ]
}