"""empty message

Revision ID: 4c08af871a9e
Revises: eb1a6567456c
Create Date: 2024-02-23 11:56:53.633856

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.sql import func

# import sqlalchemy_utils
# import sqlmodel # added

# revision identifiers, used by Alembic.
revision = "4c08af871a9e"
down_revision = "eb1a6567456c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Repos
    op.drop_column("repository", "owner_id")
    op.drop_column("repository", "is_active")
    op.drop_column("repository", "installed_by")
    op.alter_column("repository", "full_name", new_column_name="name")
    op.alter_column("repository", "id", new_column_name="provider_repo_id")
    op.alter_column("repository", "installed_at", new_column_name="created_at")
    op.add_column("repository", sa.Column("id", sa.Integer, primary_key=True, nullable=False))
    op.create_index(op.f("ix_repository_provider_repo_id"), "repository", ["provider_repo_id"], unique=False)
    # Guidelines
    op.drop_column("guideline", "repo_id")
    op.drop_column("guideline", "title")
    op.alter_column("guideline", "details", new_column_name="content")
    op.drop_column("guideline", "order")
    # User
    op.alter_column("user", "id", new_column_name="provider_user_id")
    op.alter_column("user", "provider_user_id", existing_type=sa.String(), nullable=True)
    op.add_column("user", sa.Column("id", sa.Integer, primary_key=True, nullable=False))
    op.alter_column("user", "login", existing_type=sa.String(), nullable=True)
    op.drop_index(op.f("ix_user_login"), table_name="user")
    op.alter_column("user", "hashed_password", existing_type=sa.String(), nullable=True)
    op.add_column(
        "user", sa.Column("created_at", sa.DateTime(timezone=True), server_default=func.now(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Repos
    op.drop_column("repository", "id")
    op.add_column("repository", sa.Column("owner_id", sa.Integer, nullable=False))
    op.add_column("repository", sa.Column("is_active", sa.Boolean, nullable=False, server_default=sa.false()))
    op.add_column("repository", sa.Column("installed_by", sa.Integer, nullable=False))
    op.alter_column("repository", "provider_repo_id", new_column_name="id")
    op.alter_column("repository", "name", new_column_name="full_name")
    op.alter_column("repository", "created_at", new_column_name="installed_at")
    op.drop_index(op.f("ix_repository_provider_repo_id"), table_name="repository")
    # Guidelines
    op.add_column("guideline", sa.Column("repo_id", sa.Integer, nullable=False))
    op.add_column("guideline", sa.Column("title", sa.Integer, nullable=False))
    op.alter_column("guideline", "content", new_column_name="details")
    op.add_column("guideline", sa.Column("order", sa.Integer, nullable=False))
    # User
    op.alter_column("user", "login", existing_type=sa.String(), nullable=False)
    op.create_index(op.f("ix_user_login"), "user", ["login"], unique=False)
    op.alter_column("user", "hashed_password", existing_type=sa.String(), nullable=False)
    op.drop_column("user", "created_at")
    op.drop_column("user", "id")
    op.alter_column("user", "provider_user_id", new_column_name="id")

    # ### end Alembic commands ###
